spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/santa_db
    username: hits_user
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

